version: '3.8'

services:
  odysseygo:
    image: odysseygo:develop
    container_name: odysseygo
    restart: unless-stopped
    environment:
      - NETWORK=testnet
      - RPC_ACCESS=public
      - STATE_SYNC=on
      - IP_MODE=static
      - PUBLIC_IP=42.108.76.8
      - DB_DIR=/odysseygo/db
      - LOG_LEVEL_NODE=info
      - LOG_LEVEL_DCHAIN=info
      - INDEX_ENABLED=false
      - ARCHIVAL_MODE=false
      - ADMIN_API=false
      - ETH_DEBUG_RPC=false
    # volumes:
    #   - ./data/.odysseygo:/odysseygo/.odysseygo
    #   - ./data/odyssey-node:/odysseygo/odyssey-node
    #   - ./data/db:/odysseygo/db
    #   - ./logs:/var/log/odysseygo
    ports:
      - "9650:9650"
      - "9651:9651"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9650"]
    #   interval: 60s
    #   timeout: 30s
    #   retries: 3
